### ISSUE TITLE
No voiced countdown sound

### ISSUE THREAD

**Issue by eatwithforks** [Bio2hazard/talis.xivplugin.twintania#11]
Using the latest twintania plugin from http://www.chapterfain.com/files/Talis.XIVPlugin.Twintania.zip. I am not able to hear any countdowns, i.e divebomb countdown, twister countdown, deathsentence countdown.

However, I am able to hear "Deathsentence", "Deathsentence coming", "Divebomb", anything in the twintania app that lets me choose the sound file to play.
1. I unblocked the files and extracted the plugin to the correct folder.
2. I toggled the on/off for warning and counting timers.
3. I uninstalled the installed the plugin via the updates tab
4. I click on Twintania tab -> Divebomb settings -> Enable Divebomb voiced countdown to "ON", and clicked start test. I don't hear the 5,4,3,2,1 but I do hear "Divebomb" at the end of the overlay displayed countdown.

I'm using version 3.0.5149.22159 ffxiv app but I can't get any countdown sounds, what am I doing wrong?

**Comment by Gadwin** [comment]
Same here but for every sound since the last update (or maybe the one just before, i dont remember) :'(

**Comment by Bio2hazard** [comment]
This should be fixed in the new version. Please download the update directly through FFXIVAPP, then click on the new "Reset Settings" button on the settings page of the Twintania Plugin.

After that, the sounds should work again.

Please let me know whether or not this resolved your problem. :)

**Comment by Gadwin** [comment]
thanks !

**Comment by Gadwin** [comment]
Everything works now for me ^^

**Comment by Bio2hazard** [comment]
Excellent, happy to hear. Thank you for letting me know. :) 
Lets hope that this resolves eatwithforks issue as well.

**Comment by eatwithforks** [comment]
Yup, everything works perfectly now. Thanks!
