### ISSUE TITLE
Divebomb timers

### ISSUE THREAD

**Issue by ginkeltjes** [Bio2hazard/talis.xivplugin.twintania#14]
Hello it seems they keep resetting to 68 instead of 6.8 so the timers are way of.. The dot ( . ) seems to be removed after saving the timers..

**Comment by Bio2hazard** [comment]
Hey,

this is probably because .NET and Twintania Plugin look at the regional settings for numbers and decides based on that whether a comma or a dot should be used.

Could you try a comma ( 6,8 ) and see if that fixes it?

**Comment by ginkeltjes** [comment]
Seems to work!
