### ISSUE TITLE
Enrage Timer is not working

### ISSUE THREAD

**Issue by Bio2hazard** [Bio2hazard/talis.xivplugin.twintania#2]
It seems like the IsClaimed - ActorEntity no longer works, breaking my implementation of determining when the combat started.

Will get it sorted out!

**Comment by Icehunter** [comment]
nooo~!

I'll have a look as well >.>

**Comment by Icehunter** [comment]
if(actor.IsClaimed || partyMemberList.Any(p => p.ID == actor.TargetID)) ?

Going to dig around and see if it's moved but it shouldn't have.

**Comment by Bio2hazard** [comment]
Hey,

I had my plugin dump out mob information during a twintania attempt.

```
            NLog.LogManager.GetCurrentClassLogger().Trace("Twintania:"
                + twintania.HPString + " "
                + twintania.CastingID + " "
                + twintania.CastingPercentage + " "
                + twintania.CastingProgress + " "
                + twintania.CastingTime + " "
                + twintania.IsClaimed);

            foreach (StatusEntry status in twintania.StatusEntries)
            {
                NLog.LogManager.GetCurrentClassLogger().Trace("Buff:"
                + status.StatusID + " "
                + status.CasterID + " "
                + status.Duration + " "
                + status.TargetName);
            }
```

Here is a snippet of the resulting trace log:

01:54:26.6099 0.1085|Thread 06|EventSubscriber|Twintania:513178/514596 [99.72 %] 0 0 0 0 False|00:00:15.3660985
01:54:26.6099 0.0001|Thread 06|EventSubscriber|Buff:10 3758096384 0 |00:00:15.3660985
01:54:26.6099 0.0001|Thread 06|EventSubscriber|Buff:51 268683421 18.08398 |00:00:15.3660985
01:54:26.7169 0.1066|Thread 27|EventSubscriber|Twintania:513178/514596 [99.72 %] 0 0 0 0 False|00:00:15.3816986
01:54:26.7169 0.0001|Thread 27|EventSubscriber|Buff:10 3758096384 0 |00:00:15.3816986
01:54:26.7169 0.0001|Thread 27|EventSubscriber|Buff:51 268683421 17.9839 |00:00:15.3816986
01:54:26.7169 0.0001|Thread 27|EventSubscriber|Buff:1 6098 2.043093E-42 |00:00:15.3816986
01:54:26.8269 0.1098|Thread 06|EventSubscriber|Twintania:513178/514596 [99.72 %] 0 0 0 0 False|00:00:15.3972987
01:54:26.8269 0.0001|Thread 06|EventSubscriber|Buff:10 3758096384 0 |00:00:15.3972987
01:54:26.8269 0.0001|Thread 06|EventSubscriber|Buff:51 268683421 17.86695 |00:00:15.3972987
01:54:26.8269 0.0001|Thread 06|EventSubscriber|Buff:1 6100 2.047297E-42 |00:00:15.3972987
01:54:26.9329 0.1059|Thread 04|EventSubscriber|Twintania:513178/514596 [99.72 %] 0 0 0 0 False|00:00:15.4128988
01:54:26.9329 0.0026|Thread 04|EventSubscriber|Buff:10 3758096384 0 |00:00:15.4128988
01:54:26.9329 0.0001|Thread 04|EventSubscriber|Buff:51 268683421 17.76695 |00:00:15.4128988
01:54:26.9329 0.0001|Thread 04|EventSubscriber|Buff:1 6102 1.739011E-42 |00:00:15.4128988
01:54:27.0479 0.1119|Thread 06|EventSubscriber|Twintania:513178/514596 [99.72 %] 0 0 0 0 False|00:00:15.4284989
01:54:27.0479 0.0001|Thread 06|EventSubscriber|Buff:10 3758096384 0 |00:00:15.4284989
01:54:27.0479 0.0001|Thread 06|EventSubscriber|Buff:51 268683421 17.65003 |00:00:15.4284989
01:54:27.0479 0.0001|Thread 06|EventSubscriber|Buff:1 6102 1.739011E-42 |00:00:15.4284989

As you can see, it remains at False even though we are fighting here.

I did a second test where I recorded TargetID & TargetType:
                    + "TargetID: " + twintania.TargetID + " "
                    + "TargetType: " + twintania.TargetType

Before Engaging:
02:14:24.0404 0.1090|Thread 05|EventSubscriber|Twintania:514596/514596 [100.00 %] 0 0 0 0 TargetID: -1 TargetType: 7|00:00:09.4692607
02:14:24.0404 0.0001|Thread 05|EventSubscriber|Buff:10 3758096384 0 |00:00:09.4692607
02:14:24.1494 0.1085|Thread 26|EventSubscriber|Twintania:514596/514596 [100.00 %] 0 0 0 0 TargetID: -1 TargetType: 7|00:00:09.4692607
02:14:24.1494 0.0001|Thread 26|EventSubscriber|Buff:10 3758096384 0 |00:00:09.4692607
02:14:24.2574 0.1075|Thread 05|EventSubscriber|Twintania:514596/514596 [100.00 %] 0 0 0 0 TargetID: -1 TargetType: 7|00:00:09.4692607
02:14:24.2574 0.0001|Thread 05|EventSubscriber|Buff:10 3758096384 0 |00:00:09.4692607
02:14:24.3754 0.1185|Thread 08|EventSubscriber|Twintania:514596/514596 [100.00 %] 0 0 0 0 TargetID: -1 TargetType: 7|00:00:09.4692607
02:14:24.3754 0.0001|Thread 08|EventSubscriber|Buff:10 3758096384 0 |00:00:09.4692607
02:14:24.4774 0.1021|Thread 30|EventSubscriber|Twintania:514596/514596 [100.00 %] 0 0 0 0 TargetID: -1 TargetType: 7|00:00:09.4692607
02:14:24.4774 0.0001|Thread 30|EventSubscriber|Buff:10 3758096384 0 |00:00:09.4692607

Then, for some reason TargetType changed to "True", but TargetID remained at -1:

02:14:24.5844 0.1068|Thread 26|EventSubscriber|Twintania:514596/514596 [100.00 %] 0 0 0 0 TargetID: -1 TargetType: True|00:00:09.4692607
02:14:24.5844 0.0001|Thread 26|EventSubscriber|Buff:10 3758096384 0 |00:00:09.4692607
02:14:24.6994 0.1145|Thread 24|EventSubscriber|Twintania:514596/514596 [100.00 %] 0 0 0 0 TargetID: -1 TargetType: True|00:00:09.4692607
02:14:24.6994 0.0001|Thread 24|EventSubscriber|Buff:10 3758096384 0 |00:00:09.4692607
02:14:24.8124 0.1134|Thread 05|EventSubscriber|Twintania:514596/514596 [100.00 %] 0 0 0 0 TargetID: -1 TargetType: True|00:00:09.4692607
02:14:24.8124 0.0002|Thread 05|EventSubscriber|Buff:10 3758096384 0 |00:00:09.4692607
02:14:24.9144 0.1013|Thread 30|EventSubscriber|Twintania:514596/514596 [100.00 %] 0 0 0 0 TargetID: -1 TargetType: True|00:00:09.4692607
02:14:24.9144 0.0001|Thread 30|EventSubscriber|Buff:10 3758096384 0 |00:00:09.4692607
02:14:25.0234 0.1089|Thread 28|EventSubscriber|Twintania:514596/514596 [100.00 %] 0 0 0 0 TargetID: -1 TargetType: True|00:00:09.4692607
02:14:25.0234 0.0001|Thread 28|EventSubscriber|Buff:10 3758096384 0 |00:00:09.4692607
02:14:25.1304 0.1068|Thread 32|EventSubscriber|Twintania:514596/514596 [100.00 %] 0 0 0 0 TargetID: -1 TargetType: True|00:00:09.4692607
02:14:25.1304 0.0001|Thread 32|EventSubscriber|Buff:10 3758096384 0 |00:00:09.4692607

Then, I engaged Twintania ( I suicided just to get delicious data! :D )

02:14:33.4289 0.1051|Thread 05|EventSubscriber|Twintania:514596/514596 [100.00 %] 0 0 0 0 TargetID: 268814298 TargetType: True|00:00:10.2492657
02:14:33.4289 0.0001|Thread 05|EventSubscriber|Buff:10 3758096384 0 |00:00:10.2492657
02:14:33.5409 0.1116|Thread 21|EventSubscriber|Twintania:514596/514596 [100.00 %] 0 0 0 0 TargetID: 268814298 TargetType: True|00:00:10.2492657
02:14:33.5409 0.0001|Thread 21|EventSubscriber|Buff:10 3758096384 0 |00:00:10.2492657
02:14:33.6499 0.1088|Thread 05|EventSubscriber|Twintania:514596/514596 [100.00 %] 0 0 0 0 TargetID: 268814298 TargetType: True|00:00:10.2492657
02:14:33.6499 0.0001|Thread 05|EventSubscriber|Buff:10 3758096384 0 |00:00:10.2492657
02:14:33.7609 0.1108|Thread 32|EventSubscriber|Twintania:514596/514596 [100.00 %] 0 0 0 0 TargetID: 268814298 TargetType: True|00:00:10.2492657
02:14:33.7609 0.0001|Thread 32|EventSubscriber|Buff:10 3758096384 0 |00:00:10.2492657
02:14:33.8659 0.1051|Thread 23|EventSubscriber|Twintania:514596/514596 [100.00 %] 0 0 0 0 TargetID: 268814298 TargetType: True|00:00:10.2492657
02:14:33.8659 0.0001|Thread 23|EventSubscriber|Buff:10 3758096384 0 |00:00:10.2492657
02:14:33.9799 0.1137|Thread 32|EventSubscriber|Twintania:514596/514596 [100.00 %] 0 0 0 0 TargetID: 268814298 TargetType: True|00:00:10.2492657
02:14:33.9799 0.0001|Thread 32|EventSubscriber|Buff:10 3758096384 0 |00:00:10.2492657
02:14:34.0869 0.1069|Thread 24|EventSubscriber|Twintania:514596/514596 [100.00 %] 0 0 0 0 TargetID: 268814298 TargetType: True|00:00:10.2492657
02:14:34.0869 0.0001|Thread 24|EventSubscriber|Buff:10 3758096384 0 |00:00:10.2492657
02:14:34.1949 0.1078|Thread 07|EventSubscriber|Twintania:514596/514596 [100.00 %] 0 0 0 0 TargetID: 268814298 TargetType: True|00:00:10.2492657
02:14:34.1949 0.0001|Thread 07|EventSubscriber|Buff:10 3758096384 0 |00:00:10.2492657

And after I died it went back to -1 & True:

02:14:40.6413 0.1086|Thread 10|EventSubscriber|Twintania:514352/514596 [99.95 %] 0 0 0 0 TargetID: -1 TargetType: True|00:00:10.8732697
02:14:40.6413 0.0001|Thread 10|EventSubscriber|Buff:10 3758096384 0 |00:00:10.8732697
02:14:40.6413 0.0001|Thread 10|EventSubscriber|Buff:189 268814298 24.84998 |00:00:10.8732697
02:14:40.6413 0.0001|Thread 10|EventSubscriber|Buff:179 268814298 15.84998 |00:00:10.8732697
02:14:40.6413 0.0001|Thread 10|EventSubscriber|Buff:1 9309 1.73761E-42 |00:00:10.8732697
02:14:40.7453 0.1034|Thread 26|EventSubscriber|Twintania:514352/514596 [99.95 %] 0 0 0 0 TargetID: -1 TargetType: True|00:00:10.8888698
02:14:40.7453 0.0001|Thread 26|EventSubscriber|Buff:10 3758096384 0 |00:00:10.8888698
02:14:40.7453 0.0001|Thread 26|EventSubscriber|Buff:189 268814298 24.75007 |00:00:10.8888698
02:14:40.7453 0.0001|Thread 26|EventSubscriber|Buff:179 268814298 15.75007 |00:00:10.8888698
02:14:40.7453 0.0001|Thread 26|EventSubscriber|Buff:1 9309 1.73761E-42 |00:00:10.8888698
02:14:40.8643 0.1187|Thread 22|EventSubscriber|Twintania:514352/514596 [99.95 %] 0 0 0 0 TargetID: -1 TargetType: True|00:00:10.8888698
02:14:40.8643 0.0001|Thread 22|EventSubscriber|Buff:10 3758096384 0 |00:00:10.8888698
02:14:40.8643 0.0001|Thread 22|EventSubscriber|Buff:189 268814298 24.63394 |00:00:10.8888698
02:14:40.8643 0.0001|Thread 22|EventSubscriber|Buff:179 268814298 15.63394 |00:00:10.8888698
02:14:40.8643 0.0001|Thread 22|EventSubscriber|Buff:1 9309 1.73761E-42 |00:00:10.8888698

Can you explain a bit more what TargetType indicates, especially when it changes from "7" to "True" ?

**Comment by Icehunter** [comment]
Do you have skype? I'll send my name over reddit pm ^^

**Comment by Bio2hazard** [comment]
Should be fixed in the last FFXIV-APP update! Thanks Icehunter!
