### ISSUE TITLE
Question about the language supported

### ISSUE THREAD

**Issue by Gadwin** [Bio2hazard/talis.xivplugin.twintania#4]
Hi ^^

My next T5 run will be thursday so i have to ask you to know the answer : Does this plugin works with other languages ​​or only english? If it only works with the english client, is it possible for you to create a file with all sentences  needed so we can do a translation that you could include in the plugin ?

Also i know it's not for now but is there an estimation of the time you will need to create the timer for the Dread Knight and for the Death Sentence ? ^^

Thanks

**Comment by Bio2hazard** [comment]
Hey,

it _should_ work with all languages, but I havn't had the chance to test it so I can't guarantee it.

https://github.com/Bio2hazard/talis.xivplugin.twintania/blob/master/talis.xivplugin.twintania/Utilities/LogPublisher.cs

It captures Twintania and the Dread Knight by their NPC ID, not by their name. And then it grabs their name from memory, and scans for "<Twintanias name from memory>" and "<Any of the 4 language variants of divebomb / twister>".

This means that so long as the language doesn't swap the position of monster name & skill name, it should work.

( So Twintania readies Divebomb will work, Divebomb is readied by Twintania wouldn't work - unfortunately I don't know the specifics of how the other languages work, so I don't know if this will be a problem. )

If you get to try it out, please let me know whether it worked or not and what language you used!

**Comment by Gadwin** [comment]
Hi ^^

The order of element should be the same. In french, it's always "Name of mob" prépare (= readie) "Name of skill"

I will confirm that evertthing works as soon i will do the T5 ^^

**Comment by Gadwin** [comment]
We finally did a T5 today and i can confirm that every feature listed works in french ^^
