### ISSUE TITLE
[Suggestion] Hide anchors like other FFXIV widgets

### ISSUE THREAD

**Issue by ithorien** [Bio2hazard/talis.xivplugin.twintania#7]
Just to fall in line with the rest of FFXIV widgets, it would be awesome to be able to hide the anchor on your plugin as well!

**Comment by Bio2hazard** [comment]
I have added this functionality in the latest (beta) version.

Please bear in mind that it's a beta release and not fully tested. If you'd like to help test, you can grab the beta version @ http://www.chapterfain.com/files/Talis.XIVPlugin.Twintania_Beta.zip

Let me know if it works and does what you want. :)

**Comment by Airex** [comment]
This Beta does not start. Tried to get error from logs, but nothing informative.
Just
Dispatcher.ExceptionFilter => App.OnUnhandledExceptionFilter => Logging.Log 
Dispatcher.CatchException => App.OnDispatcherUnhandledException => Logging.Log

**Comment by Bio2hazard** [comment]
Updated the link to where it'll work regardless of culture setting.
The not starting issue is elaborated on in issue #9
