### ISSUE TITLE
Invalid parse of double values from settings with different locale settings

### ISSUE THREAD

**Issue by Airex** [Bio2hazard/talis.xivplugin.twintania#9]
I found problem with loading settings.
My PC has RU locale and uses "," as decimal separator. In this case you store Default settings for double with "." as decimal separator. Convert.ToDouble uses my locale to parse string and fails with unhandled exception.

In this case if you want to hardcode settings with predefined number formatting, then it is better to force number formatting for Convert.ToDouble

**Comment by Icehunter** [comment]
I believe in this and for future releases of FFXIVAPP I will be setting NumberStyles.Any which should accept commas :)

**Comment by Bio2hazard** [comment]
Hey,

I actually figured out this bug on reddit @ http://www.reddit.com/r/ffxivapp/comments/1vho9h/twintania_boss_mod_beta_v3051312581_release_death/cesxaug just before you made this github issue. :)

My code fix contains a bit more than this pull request, but does essentially the same thing.

I've also updated the download link, so http://www.chapterfain.com/files/Talis.XIVPlugin.Twintania_Beta.zip will get you the updated version.

Thanks a ton for reporting it regardless. If you could test the new beta version and let me know if it fixes the issue, that'd be great!

**Comment by Airex** [comment]
This works for me
